### ISSUE TITLE
Optimize jumps for branch prediction

### ISSUE THREAD

**Issue by jspam** [MiniJavaInScala/mjis#257]

**Comment by Kha** [comment]
Actually, #262 didn't really change anything because reverse post-order means both jumps will always point downwards :) . In order to place the loop header below the body, we could do it like the annotated gcc fannkuch code: first generate the header for the first iteration, then the body, then the general header. This has the additional advantage that loops that will never be entered can be identified by constant folding.

**Comment by jspam** [comment]
Ah, I see. We'd need some annotation for loop headers then, the WIP register allocator assumes a block with a predecessor that comes after it in the reverse postorder is a loop header.

**Comment by Kha** [comment]
Actually actually, disregard that. The jumps are in the correct direction, the only thing switching loop header and body does (apart from the constant folding) is saving an unconditional jump.
